### ISSUE TITLE
Project settings are not visible after OS update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [stuckyb/seqtrace#8]
```
When I first downloaded and used Seqtrace (0.9.0) I had Kubuntu 12.04 and 
everything worked just fine. So I updated it to Kubuntu 14.04 and since then 
the numbers inside text boxes in "Project settings" are invisible (see attached 
image). It happens whenever I am starting a new project or opening an old one. 
On either case the default settings, my old project settings, or newly created 
project settings appear to be there due the behavior of the consensus 
generation, but the fact that the numbers won't show up next time I open the 
dialog remains annoying.

I supposed the issue could be due the update, some confusion with the python 
packages, but recently I have installed a new, fresh-formatted Kubuntu 14.04 
and the problem is still here. I'm guessing it's some incompatibility with a 
new version of some or any of the pythons packages in the Ubuntu repository?

Thank you in advance.
```

Original issue reported on code.google.com by `erico.p...@gmail.com` on 28 Apr 2015 at 10:39

Attachments:
- [seqtrace project settings.png](https://storage.googleapis.com/google-code-attachments/seqtrace/issue-8/comment-0/seqtrace project settings.png)

**Comment by stuckyb** [comment]
I've confirmed via a simple test program that PyGTK spin buttons still work correctly with the most recent implementation of GTK+, so there must be some weird interaction with how they are used in SeqTrace.  I'll continue digging...

**Comment by stuckyb** [comment]
I finally figured out the cause of the problem, and it is obscure, so I will document it here in some detail for future reference.  It appears that with recent releases of GTK+, the default values of the `climb_rate` (0.0) and `digits` (0) arguments to the `gtk.SpinButton()` constructor do not get properly applied when the spin button is created, thus causing the strange behavior noted by the original submitter.  Explicitly providing values for both arguments every time a new spin button is created fixed the bug.
